#create note
POST http://localhost:3000/notes/create
Content-Type: application/json

{
    "title": "noo",
    "content": "działa!"
}


###

# get all notes
GET http://localhost:3000/notes

###

# delete one note
DELETE  http://localhost:3000/notes

