export const theme = {
  colors: {
    common: {
      textColor: "#242F9B",
      // textColor: "#000",
      // textColorSecondary: "#FFF",
      textColorSecondary: "#646FD4",
      textInactive: "#A59E9E",
      secondaryTextInactive: "#8B8B8B",
      backgroundcolor: "#FFF",
      plantspagebackground: "#A3A5A8",
    },
    navigationBar: {
      primary: "#2F8F9D",
      secondary: "#82DBD8",
    },
    card: {
      primary: "#F8F3EF",
      secondary: "#F9F8F8",
      highlighted: "#EEE6E6",
      boxShadow: "0px 4px 4px 0px rgba(0, 0, 0, 0.25)",
      offer: "#FFF",
    },
    button: {
      primary: "#538D22",
      secondary: "#F9F8F8",
      textInactive: "#8B8B8B",
      hover: "#AAD576",
      secondaryHover: "#A59E9E",
      transparent: "transparent",
      addButton: "#F9F8F8",
      deleteButton: "#f41414",
    },
    input: {
      primary: "#F9F8F8",
      secondary: "#000",
      placeholder: "#9E9999",
      transparent: "transparent",
    },
    table: {
      primary: "#F5F6F7",
      secondary: "#AAD576",
      oddRow: "#F0F0F0	",
      filterButton: "#DCDCDC",
    },
  },
  size: {
    mobile: {
      xs: 10,
      sm: 12,
      md: 14,
      mdl: "16px",
      lg: "20px",
      xl: 24,
      xxl: "26px",
      titleXXs: 32,
      titleXs: 35,
      titleSm: 45,
      titleMd: 50,
      titleLg: 55,
    },
    desktop: {
      xxxs: 10,
      xxs: 12,
      xs: 14,
      sm: 16,
      mds: 18,
      md: 20,
      mdl: 24,
      lg: "26px",
      xl: "32px",
      xxl: "36px",
      xxxl: "42px",
      titleMd: "70px",
      titleLg: 80,
      titleXL: 110,
      titleXXL: 140,
    },
    common: {
      borderRadius: "5px",
      marginTop: "30px",
    },
  },
  weight: {
    light: 200,
    regular: 400,
    bold: 700,
  },
};
